name: "Issue Bot"
description: "trigger an action based on issue comment"
inputs:
  github-token:
    description: "Github token"
    required: true
  keywords:
    description: "keywords to look for in the issue"
    required: true
  action:
    description: "action to be taken when keyword is found"
    required: true

outputs:
  title:
    description: "Title of Issue"
  body:
    description: "Body of Issue"
runs:
  using: "node12"
  main: "lib/index.js"
branding:
  icon: alert-circle
  color: gray-dark
