name: "Test Issue Assign"
on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - uses: ./
        with:
          keywords: "assign test"
          action: "assign Naturalclar"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
