name: "Test Issue Label"
on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Amwam/issue-comment-action@v1.3.1
        with:
          keywords: '["/test"]'
          labels: '["test"]'
          github-token: ${{ secrets.GITHUB_TOKEN }}
