name: "Test Issue Label"
on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - run: npm run test
      - uses: ./
        with:
          keywords: "label test"
          action: "label Test"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
