name: "test-local"
on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install -g yarn
      - run: yarn
      - run: yarn build
      - uses: ./
        with:
          keywords: test
          actions: label
          github-token: "${{ secrets.GITHUB_TOKEN }}"
